# Generated by Django 2.1.3 on 2019-07-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190720_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=80)),
                ('rate', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('0', 'male'), ('1', 'female')], default='0', max_length=2)),
                ('friendly', models.IntegerField(default=0)),
                ('cheerful', models.IntegerField(default=0)),
                ('smarty', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('martial', models.CharField(choices=[('0', 'in-a-relationship'), ('1', 'single')], default='1', max_length=2)),
                ('bio', models.CharField(max_length=200)),
                ('user', models.IntegerField(default=0)),
            ],
        ),
    ]
