# Generated by Django 2.1.3 on 2019-07-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hitup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitup',
            name='allow_review',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hitup',
            name='expiration',
            field=models.DateTimeField(),
        ),
    ]
