# Generated by Django 2.1.3 on 2019-07-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190720_1708'),
        ('api', '0003_profile'),
    ]

    operations = [
    ]
